# Plugins
plugins:
  - jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "PMAPS 2022"
email: "info@pmaps2022.org"
description: "PMAPS 2022 CONFERENCE COVERS ALL ASPECTS OF PROBABILISTIC AND STATISTICAL MODELLING OF POWER SYSTEMS"
#baseurl: "/zeppelin"
url: "https://pmaps2022.org"
#permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "gdg-x.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "Electrical Energy and Power Systems Group, University of Manchester"
organizerAlternateName: "Electrical Energy and Power Systems Group, University of Manchester"
#organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "info@pmaps2022.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.eee.manchester.ac.uk/research/themes/"

# Head
metaKeywords: "event, conference, pmaps, power systems, engineering"
twitterAccount: "pmaps2022"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
#c4pUrl: "https://bit.ly/dfua-c4p"
#c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/about-pmaps/", text: "About PMAPS"}
  - {permalink: "/registration/", text: "Registration"}
  - {permalink: "/author-info/", text: "Author Info", links: [{text: "Important Dates", url: "/author-info/#important-dates"},
                                                              {text: "Technical Themes", url: "/author-info/#technical-themes"},
                                                              {text: "Call for Papers", url: "/author-info/#call-for-papers"},
                                                              {text: "Call for Tutorials", url: "/author-info/#call-for-tutorials"},
                                                              {text: "Paper Preparation", url: "/author-info/#paper-preparation"},
                                                              {text: "Review Process", url: "/author-info/#review-process"}]}
#                                                              {text: "Info for Authors", url: "/author-info/#info-authors"},
#                                                              {text: "Info for Presenters", url: "/author-info/#info-presenters"}]}
  - {permalink: "/venue-travel/", text: "Venue & Travel"}
  - {permalink: "/committees/", text: "Committees", links: [{text: "Organising Committee", url: "/committees/#local-committee"},
                                                            {text: "Steering Committee", url: "/committees/#steering-committee"},
                                                            {text: "Technical Committee", url: "/committees/#technical-committee"}]}
  - {permalink: "/programme/", text: "Programme"}
  - {permalink: "/sponsorship/", text: "Sponsorship", links: [{text: "Become sponsor", url: "/sponsorship/#become-sponsor"},
                                                              {text: "Sponsorship packages", url: "/sponsorship/#sponsorship-packages"},
                                                              {text: "Individual items & events", url: "/sponsorship/#individual-sponsorship-items"},
                                                              {text: "Our sponsors", url: "/sponsorship/#our-sponsors"}]}
  - {permalink: "/news/", text: "News"}
#  - {permalink: "/contact/", text: "Contact"}
# - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
# - {permalink: "/authors/", text: "Authors"}
# - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
# - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/contact/", text: "Contact"}
bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
#heroImage: "manchester.jpg"
heroTitle: "17th International Conference on Probabilistic Methods Applied to Power Systems, PMAPS 2022"
heroSubTitle: "Thriving in Uncertainty"
eventDate: "12-15 June 2022, Manchester, UK"
#typeoutTextValues: '"", "Season", "Ukraine", "Germany", "USA"'
#typeoutFallback: "Season"
heroButtons:
  # - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
#  - {permalink: "/registration", text: "Register"}
  - {permalink: "/#important-dates", text: "Important dates"}
  - {permalink: "/author-info/#call-for-papers", text: "Call for submissions"}
  - {permalink: "/sponsorship/#become-sponsor", text: "Become a sponsor"}

# About Block
aboutTitle: "Welcome!"
aboutBlock:
  - {title: "Keynotes", image: "conference.jpg", text: "Inspiring speakers from around the world", permalink: "keynote-speakers" }
  - {title: "Special Sessions", image: "panel.jpg", text: "A number of sessions to collaborate", permalink: "programme" }
  - {title: "Papers", image: "presentations.jpg", text: "Presentations of technical papers", permalink: "programme" }
  - {title: "Posters", image: "posters.jpg", text: "Poster session", permalink: "programme" }
  - {title: "Tutorials", image: "classroom.jpg", text: "Training and hands-on experience", permalink: "programme" }

# Statistic Block
#statisticBlockImage: "statistic.jpg"
statisticBlockImage: "schedule.jpg"
statisticBlock:
  - {count: "", specialCharacter: "", info: "Submission for papers and tutorials opens", date: "Submission opening soon"}
  - {count: "", specialCharacter: "", info: "Submission deadline for papers and tutorials", date: "15 Dec 2021"}
  - {count: "", specialCharacter: "", info: "Notification of acceptance for tutorials", date: "14 Jan 2021"}
  - {count: "", specialCharacter: "", info: "Notification of acceptance for papers", date: "15 Mar 2022"}
  - {count: "", specialCharacter: "", info: "Submission deadline for final papers", date: "15 Apr 2022"}
  - {count: "", specialCharacter: "", info: "Final tutorial presentation uploads", date: "27 May 2022"}
# - {count: "500", specialCharacter: "+", info: "attendees", detail: "from around the world"}
# - {count: "5", specialCharacter: "", info: "days", detail: "networking, learning and collaborating"}
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "experts in ..."}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus social programme"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
#rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Keynote speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
#locationBlockTitle: "Venue"
#eventLocationName: "Pendulum Hotel & Manchester Conference Centre"
#eventLocationMapLink: "https://www.google.com/maps/place/Pendulum+Hotel/@53.4740504,-2.2369738,17z/data=!3m1!5s0x487bb194f254906d:0x26868dfeb833061e!4m11!1m2!2m1!1sPendulum+Hotel+%26+Manchester+Conference+Centre+Sackville+Street,+M1+3BB+Manchester,+UK!3m7!1s0x487bb194feaccd21:0xb5bb81381f474de7!5m2!4m1!1i2!8m2!3d53.4740639!4d-2.2348167"
#eventStreetAddress: "Sackville Street, M1 3BB"
#eventAddressLocality: "Manchester, UK"
##eventAddressLocalityRegion: "Lvivska"
##eventAddressCountry: "UK"
##eventStartTime: "2022-06-12T09:00"
##eventDoorTime: "09:00"
##eventEndTime: "2022-06-16T18:00"
#eventPlaceCoordinates: "53.47423235193986, -2.234811963329779"
#mapCenterCoordinates: "53.47423235193986, -2.234811963329779"
#mapMobileCenterCoordinates: "53.47423235193986, -2.234811963329779"
#eventLocationEmbeddedMapLink: "https://www.google.co.uk/maps/d/u/0/embed?mid=15QIIbv47fC58joW79Z5vKcccyFiWxadK"

# Venue Block
#venueBlockTitle: "Venue"
venueBigImage: "manchester_uni_5.jpg"
#venueSmallImage1: "uni_place.jpg"
venueSmallImage1: "ambs.jpg"
venueSmallImage2: "manchester-skyline.jpg"
venueSmallImage3: "ambs-3.jpg"
#venueTitle: "Pendulum Hotel & Manchester Conference Centre"
#venueStreetAddress: "Sackville Street, M1 3BB, Manchester, UK"
venueTitle: "Alliance Manchester Business School"
venueStreetAddress: "Booth Street West, M15 6PB"
venueLocality: "Manchester, UK"
#venueFeatures: ["Sackville Street", "M1 3BB Manchester, UK"]
venueLink: "https://www.alliancembs.manchester.ac.uk/about/our-campus-and-facilities/conference-and-meeting-facilities/"
venueCoordinates: "53.46775855900619, -2.236099437346554"
venueMapCenterCoordinates: "53.46775855900619, -2.236099437346554"
venueEmbeddedMapLink: "https://www.google.com/maps/d/u/0/edit?mid=15QIIbv47fC58joW79Z5vKcccyFiWxadK"
venueMapLink: "https://www.google.com/maps/place/Alliance+Manchester+Business+School/@53.4676628,-2.2383096,17z/data=!3m1!4b1!4m5!3m4!1s0x487bb1ed5c9e3e1f:0xf49d1dba93bac80b!8m2!3d53.4676628!4d-2.2361209"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
#twitterHashTag: "#pmaps2022"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organisers"
partnersTitle: "Partners"
sponsorsTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
  - name: "Early Bird"
    price: "350"
    priceCurrency: "UAH"
    ticketsNumber: "150"
    ribbon: "-5%"
    buyButtonLink: "http://dfua.ticketforevent.com/"
    buyButtonText: "Buy Now"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    validFrom: "2014-08-25T10:00"
    validThrough: "2014-09-30T23:59"
  - name: "Last Chance"
    price: "450"
    priceCurrency: "UAH"
    ticketsNumber: "100"
    ribbon: "-20%"
    featured: true
    buyButtonLink: "http://dfua.ticketforevent.com/"
    buyButtonText: "Buy Now"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    validFrom: "2014-10-01T00:00"
    validThrough: "2014-10-23T23:59"
    disabled: true
  - name: "Student"
    price: "200"
    priceCurrency: "UAH"
    ticketsNumber: "50"
    buyButtonLink: "http://dfua.ticketforevent.com/"
    buyButtonText: "Buy Now"
    additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    validFrom: "2014-08-20T10:00"
    validThrough: "2014-10-23T23:59"
    soldOut: true
    soldOutText: "Sold Out"

# Footer
socialLinks:
# - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=pmaps2022", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
# - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
  - title: "Links"
    links:
      - {link: "https://ieeemce.org/planning-basics/general-guidelines/event-conduct-safety-statement/", text: "Code of Conduct"}
      #   - {link: "https://www.eee.manchester.ac.uk/research/themes/", text: "Electrical Energy and Power Systems, University of Manchester"}
      - {permalink: "/credits/", text: "Credits & Acknowledgements"}
  #   - {link: "https://www.manchester.ac.uk/", text: "University of Manchester"}
  - title: "Contacts"
    links:
      - {link: "mailto:info@pmaps2022.org", text: "Contact Us"}
      - {permalink: "/committees/#local-committee", text: "Organising Committee"}
  - title: "FAQ"
    links:
      - {permalink: "/sponsorship/#become-sponsor", text: "Become a sponsor"}
      - {link: "mailto:coc@pmaps2022.org", text: "Code of Conduct contact"}
#  - title: "Technical Sponsor"
#    links:
#      - {link: "https://www.ieee-pes.org/", text: '<img style="width: 75px !important;" src="/img/PES-logo-transparent-square.png" alt="IEEE PES">'}


# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

## Team Block
#teamBlockTitle: "About us"
#aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."
#
## Logistics Find Way Block
#findWayTitle: "Find your way here"
#findWayDistance: "Distance"
#findWayDriving: "DRIVING"
#findWayWalking: "WALKING"
#findWayBicycling: "BICYCLING"
#findWayTransit: "TRANSIT"
#findWayFindFlight: "Find Flight"
#logisticsMapCenterCoordinates: "53.46683379390191, -2.233926615619549"
#logisticsMapMobileCenterCoordinates: "53.46683379390191, -2.233926615619549"
#logisticsMapAutoDirections: false

# Logistics Direction Details Block
#directionDetailsImage: "direction-details.jpg"
directionDetailsImage: "manchester.jpg"
directionDetailsTitle: "Getting Around Manchester"
directionDetailsCards:
  - {title: "From the Airport", information: 'Airport is about 10 miles from the city centre. It is easily reachable by car, public transport or taxi. More information is available at the <a href="https://www.manchesterairport.co.uk/" target="_blank">airport website</a>.'}
  - {title: "Public Transport", information: 'It is easy to navigate Manchester city centre via <a href="https://tfgm.com/public-transport" target="_blank">public transport</a>.'}
  - {title: "Hotels", information: 'Manchester has lots of great hotels. More information will be available soon.'}
directionDetailsWideCards:
  - title: "Info"
    subCards:
      - title: "Venue"
        links:
          - {link: "https://plus.google.com/b/102444623953913144164", text: "G-Mex"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Registration"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Layout"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Map"}
      - title: "Hotels"
        links:
          - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
      - title: "Conference Dinner"
        links:
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Location"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Transport"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Extra dinner tickets"}
          - {link: "https://plus.google.com/b/102444623953913144164", text: "Contact"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
  - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
  - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
  - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didnâ€™t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
  - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
  - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
  - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
